services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-db
    restart: unless-stopped
    ports:
      - "7474:7474"  # Neo4j Browser (HTTP)
      - "7687:7687"  # Bolt protocol
    environment:
      # Set initial password (you can change this)
      NEO4J_AUTH: neo4j/neo4j123
      
      # Memory settings
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
      
      # Allow connections from any host
      NEO4J_dbms_default__listen__address: 0.0.0.0
      
      # Security settings
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      
      # APOC plugin configuration
      NEO4J_PLUGINS: '["apoc"]'
      
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    
    networks:
      - neo4j-network
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p neo4j123 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  neo4j-network:
    driver: bridge
